FROM digrouz/alpine-s6:latest
LABEL maintainer="DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG RADICALE_VERSION='v3.7.8'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm'  \
    RADICALE_VERSION="${RADICALE_VERSION}"

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    apk upgrade --no-cache && \
    apk add --no-cache --virtual=build-deps \
      py3-pip \
      py3-wheel \
    && \
    apk add --no-cache --virtual=run-deps \
      libffi \
      python3 \
    && \
    python3 -m venv /opt/radicale && \
    /opt/radicale/bin/pip install --upgrade --no-cache \
      Radicale[bcrypt,ldap]=="${RADICALE_VERSION}"  \
      argon2_cffi \
      pytz \
    && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/* 

### Volume
VOLUME ["/data"]

### Expose ports
EXPOSE 5232
