apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "docker-radicale.fullname" . }}-pvc
  labels: {{- include "docker-radicale.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
